### ISSUE TITLE
Please review hello-phoenix project

### ISSUE THREAD

**Issue by samrose** [flox-examples/hello-phoenix#1]
Pending todo: the readme and docs on floxdocs (doing both now)

**Comment by samrose** [comment]
Julien, please review this project from the dev rel perspective, and let me know what changes or examples you'd like to see.

**Comment by jurraca** [comment]
I seem to not have the correct access rights to push to this repo. Was going to put up a PR with suggestions. I can just put them inline here but it would be easier to push a branch so you can see the diff. @samrose

**Comment by samrose** [comment]
@jurraca I’ll make sure you have them in just a few here

**Comment by samrose** [comment]
Thanks this is done
